// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/child.vue')['default']
    Collapse: typeof import('./src/components/Collapse.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Father: typeof import('./src/components/father.vue')['default']
    NewModel: typeof import('./src/components/newModel.vue')['default']
    SuspenseModel: typeof import('./src/components/suspenseModel.vue')['default']
    Teleplort: typeof import('./src/components/teleplort.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Watch: typeof import('./src/components/watch.vue')['default']
  }
}

export { }
